### ISSUE TITLE
Implement SMS response parser

### ISSUE THREAD

**Issue by sitefeng** [uwblueprint/somo#16]
Validate and do error checking on the responses, if not valid reply to user with errors
  - for non-short answers validate that the reply is exactly what we're looking for Y,N or yes, no
  - If it's multiple choice or check box, make sure the letters are exactly the same
  - Parse checkbox properly, it's multiple choice but user can select multiple answers

If valid, forward to state machine for next question

**Comment by chrisjluc** [comment]
@luisasanmartin Probably a good ticket to start with (remember edge case for welcome message), since the other one is more of an epic.

**Comment by chrisjluc** [comment]
Potentially could be single method on question model that's like `is_response_valid(response)`, while the next question logic can be implemented in the ticket i linked above.
