### ISSUE TITLE
Configure Database Connection (Postgres)

### ISSUE THREAD

**Issue by katrinacrisostomo** [uwblueprint/somo#27]
https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-ruby-on-rails-application-on-ubuntu-14-04

Follow above^

The pg and postgres gems are in but we need to configure the database connection. Right now, if you `rake db:migrate` it can't connect.

**Comment by dinahshi** [comment]
The database is set up to use the default user `postgres`. This is more of a development environment setup issue than in-app changes. Developers need to have postgres installed, create a user, and then create the db before the first rake.

**Comment by katrinacrisostomo** [comment]
Oooh I see, okay, I'll close this issue and put this in the README
