### ISSUE TITLE
Create the page that allows users to edit/create a survey

### ISSUE THREAD

**Issue by ayushbhagat** [uwblueprint/somo#62]

**Comment by chrisjluc** [comment]
This should be worked on simultaneously with https://github.com/uwblueprint/somo/issues/69 if possible. The interfaces need to be created for this as well.

**Comment by ayushbhagat** [comment]
This issue has been split up into multiple issues, so I'll close it.

**Comment by hkjayakumar** [comment]
@ayushbhagat Aren't the other issues [#66 #67 #68 #69 #79] for individual pieces ? 
We still need to put them all together in the Edit/Create SurveyPage component right ? Should we make a new issue for that ?

**Comment by ayushbhagat** [comment]
No, only SurveyQuestion will be used in SelectedSurveyPage... And also I already wrote that in the new branch I have.

**Comment by hkjayakumar** [comment]
Ohh right, we're using the SelectedSurveyPage component for new surveys as well 👍
