### ISSUE TITLE
App interface structure: header, footer, divs

### ISSUE THREAD

**Issue by sitefeng** [uwblueprint/somo#7]

**Comment by ayushbhagat** [comment]
Don't have any footers, but need to implement the header similar to http://somo.herokuapp.com/.
The following steps are required in order to add a header:
1. Create a component called Header.jsx.
2. Add it to this line https://github.com/uwblueprint/somo-react/blob/master/src/App.jsx#L15.

**Comment by hkjayakumar** [comment]
Done in https://github.com/uwblueprint/somo-react/pull/4
