### ISSUE TITLE
Create models for survey, survey questions, transitions

### ISSUE THREAD

**Issue by kaivalyagandhi** [uwblueprint/somo#8]
Create survey, question, transition tables and basic CRUD operations.

**Comment by katrinacrisostomo** [comment]
refer to schema proposal doc in Google Drive: https://docs.google.com/document/d/1LqDbRuosyKwJBwEQ11vmMghHQPcx6nocAOTMWgFPy5Q/edit?usp=drive_web

**Comment by chrisjluc** [comment]
#40 

We're basing our new schema off this: http://www.vertabelo.com/blog/technical-articles/a-database-model-for-an-online-survey-part-3
